<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\User;
use App\Models\Worker;

class WorkerSeeder extends Seeder
{
    public function run(): void
    {
        $workers = [

            // ── GUWAHATI ──────────────────────────────────────────────────────────
            ['name'=>'Bikash Gogoi',       'phone'=>'9101230001','category'=>'Electrician',    'city'=>'Guwahati', 'locality'=>'Beltola',        'rate'=>750,  'rating'=>4.5,'reviews'=>21,'jobs'=>65, 'verified'=>true,  'today'=>true,  'areas'=>['Beltola','Hatigaon','Lokhra'],                   'skills'=>['Wiring','MCB Installation','Fan Fitting','AC Wiring'],            'bio'=>'Honest and punctual electrician serving Guwahati for 5+ years.'],
            ['name'=>'Dilip Kumar Das',    'phone'=>'9101230002','category'=>'Plumber',        'city'=>'Guwahati', 'locality'=>'Sixmile',         'rate'=>700,  'rating'=>4.6,'reviews'=>44,'jobs'=>140,'verified'=>true,  'today'=>true,  'areas'=>['Sixmile','Zoo Road','Ganeshguri'],               'skills'=>['Pipe Fitting','Leak Repair','Bathroom Fitting','Tap Installation'],'bio'=>'Professional plumber with expertise in all types of pipeline work.'],
            ['name'=>'Hemanta Nath',       'phone'=>'9101230003','category'=>'Carpenter',      'city'=>'Guwahati', 'locality'=>'Chandmari',       'rate'=>900,  'rating'=>4.8,'reviews'=>62,'jobs'=>200,'verified'=>true,  'today'=>true,  'areas'=>['Chandmari','Ulubari','Pan Bazar'],               'skills'=>['Furniture Making','Door Fitting','Modular Kitchen','Wood Polish'], 'bio'=>'Skilled carpenter specialising in custom furniture and kitchen cabinets.'],
            ['name'=>'Sanjay Boro',        'phone'=>'9101230004','category'=>'Painter',        'city'=>'Guwahati', 'locality'=>'Dispur',          'rate'=>850,  'rating'=>4.9,'reviews'=>55,'jobs'=>175,'verified'=>true,  'today'=>true,  'areas'=>['Dispur','Khanapara','VIP Road'],                 'skills'=>['Interior Paint','Exterior Paint','Texture Paint','Waterproofing'],'bio'=>'Professional painter with a team of 3. Full apartment painting in 2–3 days.'],
            ['name'=>'Rekha Bhuyan',       'phone'=>'9101230005','category'=>'Cleaner',        'city'=>'Guwahati', 'locality'=>'Narengi',         'rate'=>500,  'rating'=>4.6,'reviews'=>30,'jobs'=>95, 'verified'=>true,  'today'=>true,  'areas'=>['Narengi','Garchuk','Jalukbari'],                 'skills'=>['Deep Cleaning','Kitchen Cleaning','Bathroom Scrubbing'],           'bio'=>'Trustworthy and thorough house cleaner. Weekly and one-time available.'],
            ['name'=>'Mamoni Kalita',      'phone'=>'9101230006','category'=>'Cleaner',        'city'=>'Guwahati', 'locality'=>'Bhangagarh',      'rate'=>550,  'rating'=>4.7,'reviews'=>28,'jobs'=>88, 'verified'=>true,  'today'=>true,  'areas'=>['Bhangagarh','Athgaon','Silpukhuri'],             'skills'=>['Office Cleaning','Post-Construction','Glass Cleaning'],            'bio'=>'Former hotel housekeeping staff. Meticulous and fast. Brings own equipment.'],
            ['name'=>'Prodip Sarma',       'phone'=>'9101230007','category'=>'AC Technician',  'city'=>'Guwahati', 'locality'=>'Bamunimaidam',    'rate'=>900,  'rating'=>4.8,'reviews'=>50,'jobs'=>165,'verified'=>true,  'today'=>true,  'areas'=>['Bamunimaidam','Christian Basti','Noonmati'],     'skills'=>['AC Installation','Gas Refilling','AC Service','Split AC Repair'],  'bio'=>'Authorised technician for LG, Daikin, and Voltas. 10 years experience.'],
            ['name'=>'Bhupen Chetia',      'phone'=>'9101230008','category'=>'Driver',         'city'=>'Guwahati', 'locality'=>'Hengerabari',     'rate'=>600,  'rating'=>4.5,'reviews'=>18,'jobs'=>55, 'verified'=>true,  'today'=>true,  'areas'=>['Guwahati','Shillong','Tezpur'],                  'skills'=>['Car Driving','LMV License','City Routes','Long Distance'],         'bio'=>'Experienced driver with valid LMV licence. Familiar with all Guwahati routes.'],
            ['name'=>'Anita Phukan',       'phone'=>'9101230009','category'=>'Cook',           'city'=>'Guwahati', 'locality'=>'Zoo Road',         'rate'=>500,  'rating'=>4.9,'reviews'=>40,'jobs'=>130,'verified'=>true,  'today'=>true,  'areas'=>['Zoo Road','Ulubari','Rehabari'],                 'skills'=>['Assamese Cuisine','Bengali Cuisine','Tiffin Service','Catering'],  'bio'=>'Home cook specialising in Assamese and Bengali food. Tiffin and events.'],
            ['name'=>'Nirmal Tanti',       'phone'=>'9101230010','category'=>'Security Guard', 'city'=>'Guwahati', 'locality'=>'Khanapara',       'rate'=>700,  'rating'=>4.6,'reviews'=>14,'jobs'=>45, 'verified'=>true,  'today'=>true,  'areas'=>['Khanapara','Basistha','Lachit Nagar'],           'skills'=>['Night Duty','CCTV Monitoring','Gate Management','First Aid'],      'bio'=>'Ex-Army with 6 years of private security experience.'],
            ['name'=>'Prasanta Dey',       'phone'=>'9101230011','category'=>'Mason',          'city'=>'Guwahati', 'locality'=>'Nabagraha',       'rate'=>800,  'rating'=>4.3,'reviews'=>19,'jobs'=>60, 'verified'=>true,  'today'=>false, 'areas'=>['Nabagraha','Jorabat','Kalapahar'],               'skills'=>['Brick Work','Tile Fixing','Plastering','Waterproofing'],           'bio'=>'Civil work expert. Handles small repairs to full construction jobs.'],
            ['name'=>'Ritu Barman',        'phone'=>'9101230012','category'=>'Painter',        'city'=>'Guwahati', 'locality'=>'Ganeshguri',      'rate'=>700,  'rating'=>4.2,'reviews'=>12,'jobs'=>40, 'verified'=>false, 'today'=>true,  'areas'=>['Ganeshguri','GS Road','Rukmini Gaon'],           'skills'=>['Wall Putty','Emulsion Paint','Enamel Paint'],                      'bio'=>'Affordable and quality interior painter. Available on short notice.'],
            ['name'=>'Jitu Rajbongshi',    'phone'=>'9101230013','category'=>'Carpenter',      'city'=>'Guwahati', 'locality'=>'Maligaon',        'rate'=>850,  'rating'=>4.6,'reviews'=>33,'jobs'=>110,'verified'=>true,  'today'=>true,  'areas'=>['Maligaon','Azara','Jalukbari'],                  'skills'=>['Modular Kitchen','Wardrobe Fitting','Wood Polish','PVC Work'],      'bio'=>'Specialist in modular furniture and interior woodwork.'],

            // ── DIBRUGARH ─────────────────────────────────────────────────────────
            ['name'=>'Ranjit Borah',       'phone'=>'9101230014','category'=>'Electrician',    'city'=>'Dibrugarh','locality'=>'A.T. Road',       'rate'=>800,  'rating'=>4.7,'reviews'=>38,'jobs'=>120,'verified'=>true,  'today'=>true,  'areas'=>['Dibrugarh','Duliajan','Moran'],                  'skills'=>['Wiring','MCB Installation','Fan Fitting','AC Wiring'],            'bio'=>'Certified electrician with 8 years of experience in residential wiring.'],
            ['name'=>'Pranab Deka',        'phone'=>'9101230015','category'=>'Carpenter',      'city'=>'Dibrugarh','locality'=>'Lahowal',         'rate'=>700,  'rating'=>4.1,'reviews'=>11,'jobs'=>34, 'verified'=>false, 'today'=>true,  'areas'=>['Lahowal','Naharkatia','Duliajan'],               'skills'=>['Window Frame','Bed Making','Almirah Repair','Plywood Work'],       'bio'=>'Affordable and reliable carpenter. Specialised in repair and renovation.'],
            ['name'=>'Gopal Medhi',        'phone'=>'9101230016','category'=>'Mason',          'city'=>'Dibrugarh','locality'=>'Barbarua Road',   'rate'=>800,  'rating'=>4.4,'reviews'=>25,'jobs'=>80, 'verified'=>true,  'today'=>false, 'areas'=>['Dibrugarh','Chabua','Tingkhong'],                'skills'=>['Brick Work','Tile Fixing','Plastering','Waterproofing'],           'bio'=>'Civil work expert in Dibrugarh for over 9 years.'],
            ['name'=>'Priyanka Barua',     'phone'=>'9101230017','category'=>'Cook',           'city'=>'Dibrugarh','locality'=>'Graham Bazar',    'rate'=>450,  'rating'=>4.7,'reviews'=>22,'jobs'=>70, 'verified'=>true,  'today'=>true,  'areas'=>['Dibrugarh','Graham Bazar','Khanikar'],           'skills'=>['Assamese Cuisine','Fish Curry','Tiffin Service'],                  'bio'=>'Traditional Assamese home cook. Daily tiffin and special event catering.'],
            ['name'=>'Sumon Dutta',        'phone'=>'9101230018','category'=>'Plumber',        'city'=>'Dibrugarh','locality'=>'Chowkidinghee',   'rate'=>650,  'rating'=>4.3,'reviews'=>16,'jobs'=>50, 'verified'=>true,  'today'=>true,  'areas'=>['Dibrugarh','Chowkidinghee','Mohanbari'],         'skills'=>['Pipe Fitting','Leak Repair','Geyser Installation','Motor Fitting'],'bio'=>'Quick and reliable plumber available 7 days a week.'],
            ['name'=>'Kamal Hazarika',     'phone'=>'9101230019','category'=>'Electrician',    'city'=>'Dibrugarh','locality'=>'Circular Road',   'rate'=>720,  'rating'=>4.4,'reviews'=>20,'jobs'=>65, 'verified'=>true,  'today'=>true,  'areas'=>['Dibrugarh','Barbaruah','Jaipur'],                'skills'=>['Home Wiring','Inverter Setup','CCTV Wiring','Fan Fitting'],         'bio'=>'Electrical work specialist for homes and shops.'],
            ['name'=>'Ritu Gogoi',         'phone'=>'9101230020','category'=>'Cleaner',        'city'=>'Dibrugarh','locality'=>'Lepetkata',       'rate'=>450,  'rating'=>4.5,'reviews'=>15,'jobs'=>48, 'verified'=>true,  'today'=>true,  'areas'=>['Lepetkata','Duliajan','Naharkatia'],             'skills'=>['Deep Cleaning','Bathroom Scrubbing','Kitchen Cleaning'],           'bio'=>'Thorough and trustworthy house cleaner available daily.'],

            // ── JORHAT ────────────────────────────────────────────────────────────
            ['name'=>'Mridul Saikia',      'phone'=>'9101230021','category'=>'Plumber',        'city'=>'Jorhat',   'locality'=>'AT Road',         'rate'=>650,  'rating'=>4.3,'reviews'=>17,'jobs'=>52, 'verified'=>true,  'today'=>false, 'areas'=>['Jorhat','Titabor','Mariani'],                    'skills'=>['Geyser Installation','Overhead Tank','Motor Fitting','Drain Cleaning'],'bio'=>'Quick response and quality work guaranteed.'],
            ['name'=>'Deepak Baruah',      'phone'=>'9101230022','category'=>'Electrician',    'city'=>'Jorhat',   'locality'=>'Gar Ali',         'rate'=>700,  'rating'=>4.5,'reviews'=>24,'jobs'=>78, 'verified'=>true,  'today'=>true,  'areas'=>['Jorhat','Gar Ali','Teok'],                       'skills'=>['Wiring','DB Box','Solar Connection','Emergency Repair'],           'bio'=>'Reliable electrician covering Jorhat town and nearby areas.'],
            ['name'=>'Purnima Das',        'phone'=>'9101230023','category'=>'Cook',           'city'=>'Jorhat',   'locality'=>'Cinnamara',       'rate'=>400,  'rating'=>4.6,'reviews'=>18,'jobs'=>55, 'verified'=>true,  'today'=>true,  'areas'=>['Jorhat','Cinnamara','Borholla'],                 'skills'=>['Assamese Cuisine','Tiffin Service','Party Catering'],              'bio'=>'Tiffin and catering service with a home-cooked feel.'],
            ['name'=>'Anil Phukan',        'phone'=>'9101230024','category'=>'Carpenter',      'city'=>'Jorhat',   'locality'=>'Tarajan',         'rate'=>750,  'rating'=>4.2,'reviews'=>10,'jobs'=>32, 'verified'=>false, 'today'=>true,  'areas'=>['Jorhat','Tarajan','Mariani'],                    'skills'=>['Furniture Repair','Door Fitting','Plywood Work'],                  'bio'=>'Affordable carpenter for repairs and new furniture.'],
            ['name'=>'Bikram Borthakur',   'phone'=>'9101230025','category'=>'Mason',          'city'=>'Jorhat',   'locality'=>'Bhakat Gaon',     'rate'=>750,  'rating'=>4.0,'reviews'=>8, 'jobs'=>28, 'verified'=>true,  'today'=>false, 'areas'=>['Jorhat','Bhakat Gaon','Titabor'],                'skills'=>['Brick Work','Tile Fixing','Plastering'],                           'bio'=>'Experienced mason for residential construction and repair.'],

            // ── TINSUKIA ──────────────────────────────────────────────────────────
            ['name'=>'Arup Hazarika',      'phone'=>'9101230026','category'=>'Painter',        'city'=>'Tinsukia', 'locality'=>'Mahabhairab Road','rate'=>750,  'rating'=>4.4,'reviews'=>22,'jobs'=>70, 'verified'=>true,  'today'=>false, 'areas'=>['Tinsukia','Digboi','Margherita'],                'skills'=>['Wall Putty','Emulsion Paint','Enamel Paint','Stencil Work'],       'bio'=>'Neat and precise painter. Only branded paints — Asian, Berger, Nerolac.'],
            ['name'=>'Ramen Doley',        'phone'=>'9101230027','category'=>'Electrician',    'city'=>'Tinsukia', 'locality'=>'Doomdooma',       'rate'=>700,  'rating'=>4.3,'reviews'=>14,'jobs'=>45, 'verified'=>true,  'today'=>true,  'areas'=>['Tinsukia','Doomdooma','Makum'],                  'skills'=>['Wiring','Short Circuit Repair','MCB','Fan Fitting'],               'bio'=>'Reliable electrician in Tinsukia and Doomdooma area.'],
            ['name'=>'Binita Gogoi',       'phone'=>'9101230028','category'=>'Cleaner',        'city'=>'Tinsukia', 'locality'=>'Sootea Road',     'rate'=>450,  'rating'=>4.4,'reviews'=>12,'jobs'=>38, 'verified'=>true,  'today'=>true,  'areas'=>['Tinsukia','Digboi','Doomdooma'],                 'skills'=>['Deep Cleaning','Office Cleaning','Bathroom Scrubbing'],            'bio'=>'Professional cleaner covering Tinsukia town and nearby areas.'],
            ['name'=>'Ajit Borpujari',     'phone'=>'9101230029','category'=>'Plumber',        'city'=>'Tinsukia', 'locality'=>'Namrup',          'rate'=>600,  'rating'=>4.1,'reviews'=>9, 'jobs'=>28, 'verified'=>false, 'today'=>true,  'areas'=>['Tinsukia','Namrup','Doom Dooma'],                'skills'=>['Pipe Fitting','Tap Repair','Drain Cleaning','Overhead Tank'],      'bio'=>'Quick and affordable plumber available any day.'],

            // ── SILCHAR ───────────────────────────────────────────────────────────
            ['name'=>'Ratan Sinha',        'phone'=>'9101230030','category'=>'Electrician',    'city'=>'Silchar',  'locality'=>'Rangirkhari',     'rate'=>700,  'rating'=>4.5,'reviews'=>26,'jobs'=>85, 'verified'=>true,  'today'=>true,  'areas'=>['Silchar','Rangirkhari','Sonai'],                 'skills'=>['Wiring','Light Fitting','AC Wiring','MCB Installation'],           'bio'=>'Experienced electrician serving Silchar and Barak Valley.'],
            ['name'=>'Mita Datta',         'phone'=>'9101230031','category'=>'Cook',           'city'=>'Silchar',  'locality'=>'Meherpur',        'rate'=>420,  'rating'=>4.7,'reviews'=>20,'jobs'=>65, 'verified'=>true,  'today'=>true,  'areas'=>['Silchar','Meherpur','Ghungoor'],                 'skills'=>['Bengali Cuisine','Tiffin Service','Catering'],                     'bio'=>'Authentic Bengali cuisine. Tiffin, parties, and daily cooking.'],
            ['name'=>'Subhas Roy',         'phone'=>'9101230032','category'=>'Carpenter',      'city'=>'Silchar',  'locality'=>'Tarapur',         'rate'=>750,  'rating'=>4.3,'reviews'=>14,'jobs'=>45, 'verified'=>true,  'today'=>true,  'areas'=>['Silchar','Tarapur','Cachar'],                    'skills'=>['Furniture Making','Door Fitting','Plywood Work','Wood Polish'],     'bio'=>'Skilled carpenter for all residential needs in Silchar.'],
            ['name'=>'Kaushik Choudhury',  'phone'=>'9101230033','category'=>'Mason',          'city'=>'Silchar',  'locality'=>'Ambicapatty',     'rate'=>780,  'rating'=>4.2,'reviews'=>11,'jobs'=>35, 'verified'=>true,  'today'=>false, 'areas'=>['Silchar','Ambicapatty','Udharband'],             'skills'=>['Brick Work','Tile Fixing','Plastering','Waterproofing'],           'bio'=>'Construction and renovation specialist in Silchar.'],
            ['name'=>'Puja Laskar',        'phone'=>'9101230034','category'=>'Cleaner',        'city'=>'Silchar',  'locality'=>'Link Road',       'rate'=>430,  'rating'=>4.5,'reviews'=>16,'jobs'=>50, 'verified'=>true,  'today'=>true,  'areas'=>['Silchar','Link Road','Hailakandi Road'],         'skills'=>['Deep Cleaning','Kitchen Cleaning','Office Cleaning'],              'bio'=>'Professional and dependable house and office cleaner.'],

            // ── NAGAON ────────────────────────────────────────────────────────────
            ['name'=>'Hemen Rajkhowa',     'phone'=>'9101230035','category'=>'Electrician',    'city'=>'Nagaon',   'locality'=>'Haibargaon',      'rate'=>650,  'rating'=>4.3,'reviews'=>15,'jobs'=>48, 'verified'=>true,  'today'=>true,  'areas'=>['Nagaon','Haibargaon','Kaliabor'],                'skills'=>['Wiring','Fan Fitting','Light Fitting','Short Circuit Repair'],     'bio'=>'Honest electrician serving Nagaon district for 6 years.'],
            ['name'=>'Dipali Bora',        'phone'=>'9101230036','category'=>'Cleaner',        'city'=>'Nagaon',   'locality'=>'Pub Nagaon',      'rate'=>400,  'rating'=>4.4,'reviews'=>12,'jobs'=>38, 'verified'=>true,  'today'=>true,  'areas'=>['Nagaon','Pub Nagaon','Chaparmukh'],              'skills'=>['Deep Cleaning','Bathroom Scrubbing','Kitchen Cleaning'],           'bio'=>'Reliable cleaner available daily in Nagaon area.'],
            ['name'=>'Nabin Hazarika',     'phone'=>'9101230037','category'=>'Plumber',        'city'=>'Nagaon',   'locality'=>'Court Road',      'rate'=>600,  'rating'=>4.1,'reviews'=>9, 'jobs'=>28, 'verified'=>false, 'today'=>true,  'areas'=>['Nagaon','Kampur','Doboka'],                      'skills'=>['Pipe Fitting','Leak Repair','Tap Installation','Drain Cleaning'],  'bio'=>'Quick plumber covering Nagaon and nearby areas.'],
            ['name'=>'Pranjal Chetia',     'phone'=>'9101230038','category'=>'Cook',           'city'=>'Nagaon',   'locality'=>'Nowgong',         'rate'=>380,  'rating'=>4.5,'reviews'=>14,'jobs'=>44, 'verified'=>true,  'today'=>true,  'areas'=>['Nagaon','Nowgong','Raha'],                       'skills'=>['Assamese Cuisine','Fish Preparation','Tiffin Service'],            'bio'=>'Home cook offering daily tiffin and Assamese meals.'],

            // ── SIVASAGAR ─────────────────────────────────────────────────────────
            ['name'=>'Dulal Borah',        'phone'=>'9101230039','category'=>'Carpenter',      'city'=>'Sivasagar','locality'=>'AT Road',         'rate'=>720,  'rating'=>4.4,'reviews'=>18,'jobs'=>56, 'verified'=>true,  'today'=>true,  'areas'=>['Sivasagar','Nazira','Amguri'],                   'skills'=>['Furniture Making','Door Fitting','Modular Kitchen','Almirah'],     'bio'=>'Custom furniture and kitchen cabinet specialist.'],
            ['name'=>'Runumi Deka',        'phone'=>'9101230040','category'=>'Cook',           'city'=>'Sivasagar','locality'=>'Heritage Road',   'rate'=>400,  'rating'=>4.6,'reviews'=>16,'jobs'=>52, 'verified'=>true,  'today'=>true,  'areas'=>['Sivasagar','Gaurisagar','Joysagar'],             'skills'=>['Assamese Cuisine','Tiffin Service','Party Food'],                  'bio'=>'Authentic Assamese cooking. Tiffin and event catering.'],
            ['name'=>'Binod Gogoi',        'phone'=>'9101230041','category'=>'Electrician',    'city'=>'Sivasagar','locality'=>'Nazira Road',     'rate'=>660,  'rating'=>4.2,'reviews'=>10,'jobs'=>32, 'verified'=>true,  'today'=>true,  'areas'=>['Sivasagar','Nazira','Sebhata'],                  'skills'=>['Wiring','MCB','Fan Fitting','Inverter Setup'],                     'bio'=>'Certified electrician for residential and commercial work.'],
            ['name'=>'Pradeep Konwar',     'phone'=>'9101230042','category'=>'Mason',          'city'=>'Sivasagar','locality'=>'Joysagar',        'rate'=>760,  'rating'=>4.1,'reviews'=>8, 'jobs'=>26, 'verified'=>false, 'today'=>false, 'areas'=>['Sivasagar','Joysagar','Amguri'],                 'skills'=>['Brick Work','Tile Fixing','Plastering'],                           'bio'=>'Experienced mason for residential and shop fit-outs.'],

            // ── TEZPUR ────────────────────────────────────────────────────────────
            ['name'=>'Kamal Nath',         'phone'=>'9101230043','category'=>'Electrician',    'city'=>'Tezpur',   'locality'=>'Mission Chariali','rate'=>680,  'rating'=>4.5,'reviews'=>22,'jobs'=>70, 'verified'=>true,  'today'=>true,  'areas'=>['Tezpur','Napam','Dhekiajuli'],                   'skills'=>['Wiring','DB Box','Emergency Repair','Solar Setup'],                'bio'=>'Reliable electrician serving Tezpur and Sonitpur district.'],
            ['name'=>'Sushmita Baruah',    'phone'=>'9101230044','category'=>'Cleaner',        'city'=>'Tezpur',   'locality'=>'Dekargaon',       'rate'=>420,  'rating'=>4.6,'reviews'=>17,'jobs'=>54, 'verified'=>true,  'today'=>true,  'areas'=>['Tezpur','Dekargaon','Biswanath'],                'skills'=>['Deep Cleaning','Kitchen Cleaning','Bathroom Scrubbing'],           'bio'=>'Trustworthy and thorough cleaner in Tezpur.'],
            ['name'=>'Pradip Talukdar',    'phone'=>'9101230045','category'=>'Plumber',        'city'=>'Tezpur',   'locality'=>'Tezpur Town',     'rate'=>620,  'rating'=>4.3,'reviews'=>13,'jobs'=>40, 'verified'=>true,  'today'=>true,  'areas'=>['Tezpur','Dhekiajuli','Biswanath Chariali'],     'skills'=>['Pipe Fitting','Leak Repair','Motor Fitting','Drain Cleaning'],     'bio'=>'Quick and dependable plumber in Tezpur area.'],

            // ── NORTH LAKHIMPUR ───────────────────────────────────────────────────
            ['name'=>'Tapan Borah',        'phone'=>'9101230046','category'=>'Carpenter',      'city'=>'North Lakhimpur','locality'=>'Lakhimpur Town','rate'=>680, 'rating'=>4.3,'reviews'=>13,'jobs'=>40, 'verified'=>true, 'today'=>true, 'areas'=>['North Lakhimpur','Narayanpur','Ghiladhari'],   'skills'=>['Furniture Making','Door Fitting','Bed Repair'],                    'bio'=>'Reliable carpenter covering North Lakhimpur and nearby areas.'],
            ['name'=>'Mamata Devi',        'phone'=>'9101230047','category'=>'Cook',           'city'=>'North Lakhimpur','locality'=>'Kadam','rate'=>360,'rating'=>4.5,'reviews'=>11,'jobs'=>35, 'verified'=>true, 'today'=>true, 'areas'=>['North Lakhimpur','Kadam','Dhakuakhana'],        'skills'=>['Assamese Cuisine','Tiffin Service','Fish Curry'],                  'bio'=>'Daily tiffin and home cooking in North Lakhimpur.'],
            ['name'=>'Ranjit Doley',       'phone'=>'9101230048','category'=>'Electrician',    'city'=>'North Lakhimpur','locality'=>'Telahi','rate'=>620,'rating'=>4.0,'reviews'=>7, 'jobs'=>22, 'verified'=>false,'today'=>true, 'areas'=>['North Lakhimpur','Telahi','Bihpuria'],          'skills'=>['Wiring','Light Fitting','Fan Fitting'],                            'bio'=>'Affordable electrician for household electrical work.'],

            // ── BONGAIGAON ────────────────────────────────────────────────────────
            ['name'=>'Raju Sarkar',        'phone'=>'9101230049','category'=>'Plumber',        'city'=>'Bongaigaon','locality'=>'Station Road',   'rate'=>600,  'rating'=>4.2,'reviews'=>10,'jobs'=>32, 'verified'=>true,  'today'=>true,  'areas'=>['Bongaigaon','Sidli','Manikpur'],                 'skills'=>['Pipe Fitting','Leak Repair','Bathroom Fitting','Motor Fitting'],   'bio'=>'Dependable plumber in Bongaigaon for 4 years.'],
            ['name'=>'Suman Paul',         'phone'=>'9101230050','category'=>'Painter',        'city'=>'Bongaigaon','locality'=>'Abhayapuri',     'rate'=>680,  'rating'=>4.3,'reviews'=>12,'jobs'=>38, 'verified'=>true,  'today'=>true,  'areas'=>['Bongaigaon','Abhayapuri','Bijni'],               'skills'=>['Interior Paint','Exterior Paint','Wall Putty','Emulsion'],         'bio'=>'Quality painter at affordable rates in Bongaigaon.'],
            ['name'=>'Kalpana Boro',       'phone'=>'9101230051','category'=>'Cleaner',        'city'=>'Bongaigaon','locality'=>'New Bongaigaon', 'rate'=>400,  'rating'=>4.4,'reviews'=>9, 'jobs'=>28, 'verified'=>true,  'today'=>true,  'areas'=>['Bongaigaon','New Bongaigaon','Manikpur'],        'skills'=>['Deep Cleaning','Kitchen Cleaning','Office Cleaning'],              'bio'=>'Punctual and efficient house cleaner.'],

            // ── DHUBRI ────────────────────────────────────────────────────────────
            ['name'=>'Abdul Karim',        'phone'=>'9101230052','category'=>'Mason',          'city'=>'Dhubri',   'locality'=>'Dhubri Town',     'rate'=>720,  'rating'=>4.1,'reviews'=>8, 'jobs'=>25, 'verified'=>true,  'today'=>false, 'areas'=>['Dhubri','Bilasipara','Golakganj'],               'skills'=>['Brick Work','Tile Fixing','Plastering','Waterproofing'],           'bio'=>'Civil work and renovation specialist in Dhubri.'],
            ['name'=>'Rina Begum',         'phone'=>'9101230053','category'=>'Cleaner',        'city'=>'Dhubri',   'locality'=>'Gauripur',        'rate'=>380,  'rating'=>4.3,'reviews'=>8, 'jobs'=>24, 'verified'=>true,  'today'=>true,  'areas'=>['Dhubri','Gauripur','Bilasipara'],                'skills'=>['House Cleaning','Kitchen Cleaning','Bathroom Scrubbing'],          'bio'=>'Reliable house cleaner in Dhubri and Gauripur.'],
            ['name'=>'Azizul Islam',       'phone'=>'9101230054','category'=>'Electrician',    'city'=>'Dhubri',   'locality'=>'Bilasipara Road', 'rate'=>620,  'rating'=>4.0,'reviews'=>7, 'jobs'=>22, 'verified'=>false, 'today'=>true,  'areas'=>['Dhubri','Bilasipara','Agomani'],                 'skills'=>['Wiring','Fan Fitting','MCB Installation','Light Fitting'],         'bio'=>'Affordable electrician for homes and small shops.'],

            // ── GOALPARA ──────────────────────────────────────────────────────────
            ['name'=>'Sarat Das',          'phone'=>'9101230055','category'=>'Carpenter',      'city'=>'Goalpara', 'locality'=>'Krishnai',        'rate'=>660,  'rating'=>4.2,'reviews'=>9, 'jobs'=>28, 'verified'=>true,  'today'=>true,  'areas'=>['Goalpara','Krishnai','Dudhnoi'],                 'skills'=>['Furniture Making','Door Fitting','Plywood Work'],                  'bio'=>'Affordable carpenter for homes in Goalpara district.'],
            ['name'=>'Sunita Rabha',       'phone'=>'9101230056','category'=>'Cook',           'city'=>'Goalpara', 'locality'=>'Lakhipur',        'rate'=>360,  'rating'=>4.4,'reviews'=>10,'jobs'=>30, 'verified'=>true,  'today'=>true,  'areas'=>['Goalpara','Lakhipur','Krishnai'],                'skills'=>['Assamese Cuisine','Bodo Cuisine','Tiffin Service'],                'bio'=>'Assamese and Bodo specialties. Daily tiffin available.'],

            // ── KARIMGANJ ─────────────────────────────────────────────────────────
            ['name'=>'Suresh Nath',        'phone'=>'9101230057','category'=>'Plumber',        'city'=>'Karimganj','locality'=>'Patharkandi',     'rate'=>580,  'rating'=>4.2,'reviews'=>9, 'jobs'=>28, 'verified'=>true,  'today'=>true,  'areas'=>['Karimganj','Patharkandi','Nilambazar'],          'skills'=>['Pipe Fitting','Leak Repair','Tap Installation'],                   'bio'=>'Reliable plumber covering Karimganj and Patharkandi.'],
            ['name'=>'Bina Das',           'phone'=>'9101230058','category'=>'Cleaner',        'city'=>'Karimganj','locality'=>'Badarpur',        'rate'=>380,  'rating'=>4.3,'reviews'=>7, 'jobs'=>22, 'verified'=>true,  'today'=>true,  'areas'=>['Karimganj','Badarpur','Hailakandi'],             'skills'=>['Deep Cleaning','Kitchen Cleaning','Office Cleaning'],              'bio'=>'Trustworthy cleaner in Karimganj and surrounding areas.'],

            // ── GOLAGHAT ──────────────────────────────────────────────────────────
            ['name'=>'Mriganka Doley',     'phone'=>'9101230059','category'=>'Electrician',    'city'=>'Golaghat', 'locality'=>'Numaligarh',      'rate'=>660,  'rating'=>4.4,'reviews'=>14,'jobs'=>44, 'verified'=>true,  'today'=>true,  'areas'=>['Golaghat','Numaligarh','Sarupathar'],            'skills'=>['Wiring','Short Circuit Repair','MCB','Solar Setup'],               'bio'=>'Experienced electrician in Golaghat and Numaligarh.'],
            ['name'=>'Kabita Sonowal',     'phone'=>'9101230060','category'=>'Cook',           'city'=>'Golaghat', 'locality'=>'Bokakhat',        'rate'=>380,  'rating'=>4.5,'reviews'=>12,'jobs'=>38, 'verified'=>true,  'today'=>true,  'areas'=>['Golaghat','Bokakhat','Dergaon'],                 'skills'=>['Assamese Cuisine','Tiffin Service','Party Catering'],              'bio'=>'Delicious Assamese cooking. Tiffin and festive catering.'],

            // ── NALBARI ───────────────────────────────────────────────────────────
            ['name'=>'Kartik Kalita',      'phone'=>'9101230061','category'=>'Mason',          'city'=>'Nalbari',  'locality'=>'Tihu',            'rate'=>740,  'rating'=>4.2,'reviews'=>9, 'jobs'=>28, 'verified'=>true,  'today'=>true,  'areas'=>['Nalbari','Tihu','Barkhetri'],                    'skills'=>['Brick Work','Tile Fixing','Plastering','RCC Work'],                'bio'=>'Expert mason for residential construction in Nalbari.'],
            ['name'=>'Papori Baruah',      'phone'=>'9101230062','category'=>'Cleaner',        'city'=>'Nalbari',  'locality'=>'Nalbari Town',    'rate'=>390,  'rating'=>4.3,'reviews'=>8, 'jobs'=>24, 'verified'=>true,  'today'=>true,  'areas'=>['Nalbari','Tihu','Dharmapur'],                    'skills'=>['House Cleaning','Kitchen Cleaning','Bathroom Scrubbing'],          'bio'=>'Dependable cleaner in Nalbari town area.'],

            // ── BARPETA ───────────────────────────────────────────────────────────
            ['name'=>'Jayanta Das',        'phone'=>'9101230063','category'=>'Electrician',    'city'=>'Barpeta',  'locality'=>'Barpeta Road',    'rate'=>640,  'rating'=>4.3,'reviews'=>11,'jobs'=>35, 'verified'=>true,  'today'=>true,  'areas'=>['Barpeta','Barpeta Road','Sarthebari'],           'skills'=>['Wiring','Fan Fitting','Light Fitting','MCB Installation'],         'bio'=>'Local electrician serving Barpeta and Sarthebari areas.'],
            ['name'=>'Nirmali Devi',       'phone'=>'9101230064','category'=>'Cook',           'city'=>'Barpeta',  'locality'=>'Sarthebari',      'rate'=>360,  'rating'=>4.5,'reviews'=>11,'jobs'=>35, 'verified'=>true,  'today'=>true,  'areas'=>['Barpeta','Sarthebari','Mandia'],                 'skills'=>['Assamese Cuisine','Tiffin Service'],                               'bio'=>'Daily tiffin and home cooking. Simple and tasty.'],

            // ── KOKRAJHAR ─────────────────────────────────────────────────────────
            ['name'=>'Sanjit Basumatary', 'phone'=>'9101230065','category'=>'Carpenter',      'city'=>'Kokrajhar','locality'=>'Gossaigaon',      'rate'=>670,  'rating'=>4.2,'reviews'=>9, 'jobs'=>28, 'verified'=>true,  'today'=>true,  'areas'=>['Kokrajhar','Gossaigaon','Dotma'],                'skills'=>['Furniture Making','Door Fitting','Bed Repair','Plywood Work'],     'bio'=>'Carpenter serving Kokrajhar and BTC area.'],
            ['name'=>'Binita Wary',        'phone'=>'9101230066','category'=>'Cleaner',        'city'=>'Kokrajhar','locality'=>'Kokrajhar Town',  'rate'=>380,  'rating'=>4.3,'reviews'=>7, 'jobs'=>22, 'verified'=>true,  'today'=>true,  'areas'=>['Kokrajhar','Gossaigaon','Chirang'],              'skills'=>['House Cleaning','Kitchen Cleaning','Deep Cleaning'],               'bio'=>'Reliable cleaner in Kokrajhar town.'],

            // ── DIPHU ─────────────────────────────────────────────────────────────
            ['name'=>'Nirton Ronghang',    'phone'=>'9101230067','category'=>'Mason',          'city'=>'Diphu',    'locality'=>'Diphu Town',      'rate'=>730,  'rating'=>4.1,'reviews'=>7, 'jobs'=>22, 'verified'=>false, 'today'=>true,  'areas'=>['Diphu','Bokajan','Hamren'],                      'skills'=>['Brick Work','Tile Fixing','Plastering'],                           'bio'=>'Experienced mason for homes in Diphu and Karbi Anglong.'],
            ['name'=>'Phulmoni Timung',    'phone'=>'9101230068','category'=>'Cook',           'city'=>'Diphu',    'locality'=>'Harmoti',         'rate'=>360,  'rating'=>4.4,'reviews'=>9, 'jobs'=>28, 'verified'=>true,  'today'=>true,  'areas'=>['Diphu','Harmoti','Bokajan'],                     'skills'=>['Assamese Cuisine','Karbi Cuisine','Tiffin Service'],               'bio'=>'Assamese and Karbi traditional cooking. Tiffin available.'],

            // ── HAILAKANDI ────────────────────────────────────────────────────────
            ['name'=>'Samim Ahmed',        'phone'=>'9101230069','category'=>'Electrician',    'city'=>'Hailakandi','locality'=>'Lala',            'rate'=>620,  'rating'=>4.2,'reviews'=>9, 'jobs'=>28, 'verified'=>true,  'today'=>true,  'areas'=>['Hailakandi','Lala','Algapur'],                   'skills'=>['Wiring','MCB Installation','Light Fitting','Fan Fitting'],         'bio'=>'Electrician covering Hailakandi and Lala area.'],
            ['name'=>'Rajia Begum',        'phone'=>'9101230070','category'=>'Cook',           'city'=>'Hailakandi','locality'=>'Hailakandi Town', 'rate'=>360,  'rating'=>4.4,'reviews'=>8, 'jobs'=>24, 'verified'=>true,  'today'=>true,  'areas'=>['Hailakandi','Lala','Sonai'],                     'skills'=>['Bengali Cuisine','Rice Dishes','Tiffin Service'],                  'bio'=>'Authentic Bengali cooking. Daily tiffin in Hailakandi.'],

            // ── MORIGAON ──────────────────────────────────────────────────────────
            ['name'=>'Biren Pegu',         'phone'=>'9101230071','category'=>'Electrician',    'city'=>'Morigaon', 'locality'=>'Jagiroad',        'rate'=>640,  'rating'=>4.2,'reviews'=>10,'jobs'=>31, 'verified'=>true,  'today'=>true,  'areas'=>['Morigaon','Jagiroad','Mayong'],                  'skills'=>['Wiring','Fan Fitting','Short Circuit Repair'],                     'bio'=>'Dependable electrician in Morigaon and Jagiroad.'],
            ['name'=>'Priti Boro',         'phone'=>'9101230072','category'=>'Cleaner',        'city'=>'Morigaon', 'locality'=>'Morigaon Town',   'rate'=>380,  'rating'=>4.3,'reviews'=>7, 'jobs'=>22, 'verified'=>true,  'today'=>true,  'areas'=>['Morigaon','Jagiroad','Laharighat'],              'skills'=>['House Cleaning','Kitchen Cleaning','Bathroom Scrubbing'],          'bio'=>'Reliable and punctual cleaner in Morigaon.'],

            // ── MAJULI ────────────────────────────────────────────────────────────
            ['name'=>'Nipen Mising',       'phone'=>'9101230073','category'=>'Carpenter',      'city'=>'Majuli',   'locality'=>'Garamur',         'rate'=>620,  'rating'=>4.3,'reviews'=>8, 'jobs'=>25, 'verified'=>true,  'today'=>true,  'areas'=>['Majuli','Garamur','Kamalabari'],                 'skills'=>['Furniture Making','Bamboo Work','Door Fitting'],                   'bio'=>'Traditional bamboo and wood craftsman in Majuli.'],
            ['name'=>'Ananda Payeng',      'phone'=>'9101230074','category'=>'Cook',           'city'=>'Majuli',   'locality'=>'Kamalabari',      'rate'=>350,  'rating'=>4.6,'reviews'=>10,'jobs'=>30, 'verified'=>true,  'today'=>true,  'areas'=>['Majuli','Kamalabari','Garamur'],                 'skills'=>['Assamese Cuisine','Mishing Cuisine','Traditional Cooking'],        'bio'=>'Traditional Assamese and Mishing recipes. Festival catering.'],

            // ── DULIAJAN ──────────────────────────────────────────────────────────
            ['name'=>'Prabin Neog',        'phone'=>'9101230075','category'=>'Electrician',    'city'=>'Duliajan', 'locality'=>'Duliajan Town',   'rate'=>720,  'rating'=>4.5,'reviews'=>18,'jobs'=>56, 'verified'=>true,  'today'=>true,  'areas'=>['Duliajan','Naharkatia','Moran'],                 'skills'=>['Wiring','MCB Installation','AC Wiring','CCTV Wiring'],            'bio'=>'Industrial and residential electrician in Duliajan oil town.'],
            ['name'=>'Srestha Baruah',     'phone'=>'9101230076','category'=>'Cook',           'city'=>'Duliajan', 'locality'=>'ONGC Colony',     'rate'=>420,  'rating'=>4.5,'reviews'=>13,'jobs'=>40, 'verified'=>true,  'today'=>true,  'areas'=>['Duliajan','Naharkatia','Tingkhong'],             'skills'=>['Assamese Cuisine','Bengali Cuisine','Tiffin Service'],             'bio'=>'Home tiffin service popular in Duliajan and ONGC colony.'],

            // ── NAHARKATIA ────────────────────────────────────────────────────────
            ['name'=>'Bhaskar Saikia',     'phone'=>'9101230077','category'=>'Plumber',        'city'=>'Naharkatia','locality'=>'Naharkatia Town','rate'=>600,  'rating'=>4.1,'reviews'=>8, 'jobs'=>25, 'verified'=>true,  'today'=>true,  'areas'=>['Naharkatia','Panitola','Moran'],                 'skills'=>['Pipe Fitting','Leak Repair','Motor Fitting','Overhead Tank'],      'bio'=>'Reliable plumber in Naharkatia and Panitola.'],

            // ── DIGBOI ────────────────────────────────────────────────────────────
            ['name'=>'Ajoy Senapati',      'phone'=>'9101230078','category'=>'AC Technician',  'city'=>'Digboi',   'locality'=>'Digboi Town',     'rate'=>850,  'rating'=>4.5,'reviews'=>16,'jobs'=>50, 'verified'=>true,  'today'=>true,  'areas'=>['Digboi','Margherita','Tinsukia'],                'skills'=>['AC Installation','Gas Refilling','AC Service','Split AC Repair'],  'bio'=>'Authorised AC technician in Digboi and Margherita area.'],

            // ── MARGHERITA ────────────────────────────────────────────────────────
            ['name'=>'Dhan Bahadur Limbu', 'phone'=>'9101230079','category'=>'Security Guard', 'city'=>'Margherita','locality'=>'Margherita Town','rate'=>680,  'rating'=>4.4,'reviews'=>10,'jobs'=>32, 'verified'=>true,  'today'=>true,  'areas'=>['Margherita','Ledo','Digboi'],                    'skills'=>['Night Duty','Gate Management','CCTV Monitoring'],                  'bio'=>'Disciplined security guard for residences and offices.'],

            // ── BISWANATH CHARIALI ────────────────────────────────────────────────
            ['name'=>'Dilip Sarma',        'phone'=>'9101230080','category'=>'Mason',          'city'=>'Biswanath Chariali','locality'=>'Gohpur Road','rate'=>740,'rating'=>4.2,'reviews'=>9,'jobs'=>28, 'verified'=>true,  'today'=>true,  'areas'=>['Biswanath Chariali','Gohpur','Behali'],          'skills'=>['Brick Work','Tile Fixing','Plastering','Waterproofing'],           'bio'=>'Civil contractor in Biswanath Chariali for 7 years.'],

        ];

        foreach ($workers as $data) {
            $email = strtolower(str_replace([' ', '.'], ['.', ''], $data['name']))
                   . rand(10, 99)
                   . '@vastoq.worker';

            $user = User::create([
                'name'        => $data['name'],
                'phone'       => $data['phone'],
                'email'       => $email,
                'password'    => bcrypt('password'),
                'role'        => 'worker',
                'is_verified' => $data['verified'],
            ]);

            Worker::create([
                'user_id'        => $user->id,
                'category'       => $data['category'],
                'skills'         => $data['skills'],
                'bio'            => $data['bio'],
                'city'           => $data['city'],
                'locality'       => $data['locality'],
                'rate_per_day'   => $data['rate'],
                'rating'         => $data['rating'],
                'review_count'   => $data['reviews'],
                'jobs_completed' => $data['jobs'],
                'is_verified'    => $data['verified'],
                'aadhaar_status' => $data['verified'] ? 'verified' : 'pending',
                'available_today'=> $data['today'],
                'service_areas'  => $data['areas'],
                'is_active'      => true,
            ]);
        }
    }
}
